INSERT INTO students (name, course, email, gender, birth_date) VALUES ('Ronaldo Brasil', 'TSI', 'ronaldo@mail.com', 'MASCULINE', '1976-09-22'),
                                                                      ('Romário Brasil', 'TSI', 'romario@mail.com', 'MASCULINE', '1966-01-29'),
                                                                      ('Taffarel Brasil', 'TSI', 'taffarel@mail.com', 'MASCULINE', '1966-05-08'),
                                                                      ('Gilmar Brasil', 'TSI', 'gilmar@mail.com', 'MASCULINE', '1959-01-13'),
                                                                      ('Bebeto Brasil', 'TSI', 'bebeto@mail.com', 'MASCULINE', '1964-02-16'),
                                                                      ('Raí Brasil', 'TSI', 'rai@mail.com', 'MASCULINE', '1965-05-15'),
                                                                      ('Ricardo Rocha Brasil', 'TSI', 'ricardo@mail.com', 'MASCULINE', '1962-09-11'),
                                                                      ('Leonardo Brasil', 'TSI', 'leonardo@mail.com', 'MASCULINE', '1969-09-05'),
                                                                      ('Mazinho Brasil', 'TSI', 'mazinho@mail.com', 'MASCULINE', '1966-09-15'),
                                                                      ('Paulo Sérgio Brasil', 'TSI', 'paulo@mail.com', 'MASCULINE', '1969-06-02'),
                                                                      ('Zinho Brasil', 'TSI', 'zinho@mail.com', 'MASCULINE', '1967-06-17'),
                                                                      ('Jorginho Brasil', 'TSI', 'jorginho@mail.com', 'MASCULINE', '1964-08-17'),
                                                                      ('Viola Brasil', 'TSI', 'viola@mail.com', 'MASCULINE', '1969-01-01'),
                                                                      ('Muller Brasil', 'TSI', 'muller@mail.com', 'MASCULINE', '1966-01-31'),
                                                                      ('Dunga Brasil', 'TSI', 'dunga@mail.com', 'MASCULINE', '1963-10-31'),
                                                                      ('Marcio Santos Brasil', 'TSI', 'marcio@mail.com', 'MASCULINE', '1969-09-15'),
                                                                      ('Aldair Brasil', 'TSI', 'aldair@mail.com', 'MASCULINE', '1965-11-30'),
                                                                      ('Zetti Brasil', 'TSI', 'zetti@mail.com', 'MASCULINE', '1965-01-10'),
                                                                      ('Mauro Silva Brasil', 'TSI', 'mauro@mail.com', 'MASCULINE', '1968-01-12'),
                                                                      ('Cafu Brasil', 'TSI', 'cafu@mail.com', 'MASCULINE', '1970-06-19');